# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920026b48e61cdefe20646cdbe4ae7d8c2f98d72595780fd1b3a4f0a75d7144f5ae78d97042892b09acbf6c1fdd7734dd1486b7a11735222efb8c15908242bea

test:
  secret_key_base: 9cc0776a817a4f2ba84d5512c0b64aff885d41f05b0096c6121efbc050366681a1801fe0b65276f61044c43459d0b6ac6bdd814939b58e124cc443391bfcdf60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
